### ISSUE TITLE
[invalid] minus button background not displayed

### ISSUE THREAD

**Issue by hvdwolf** [sweebee/pimatic-thermostat#4]
Hi,

Something not entirely correct with the style or image of the minus button.
I cloned your repo which is automatically going into pimatic-thermostat on my webserver
Then I made a second clone "git clone https://github.com/sweebee/pimatic-thermostat.git thermostaat" to experiment with and to make the url shorter.
However, without having changed anythingyet the minus button is not displayed. The minus (-) itself is displayed. Not being a css expert like you, I could not find it.

**Comment by hvdwolf** [comment]
Stupid. I found it already. The .down is missing the padding.

.up {
        padding-top:10px;
        height: 31px;
}

.down {
        padding-top:10px;   <-- this was missing
        height: 32px;
}

**Comment by hvdwolf** [comment]
No. It is not. It is on my S5 mini but it's not on my old wolfgang.

**Comment by sweebee** [comment]
I changed lower to down. Please refresh your cache. I think that will do it.

**Comment by hvdwolf** [comment]
of course. That did it. Too much focused on the css itself
